In [194]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.datasets import make_classification
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from numpy import mean
from numpy import std
import  pickle
from joblib import dump, load

In [195]:
np_load = np.load('npz_files/feat_data.npz',allow_pickle=True) # load
#np_load = np.load('feat_data_no_zero_crossings.npz',allow_pickle=True)
X = np_load['feature_array']
y = np_load['dataset_class']
print(X.shape, y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape,X_test.shape, y_train.shape, y_test.shape)

(86, 16) (86,)
(68, 16) (18, 16) (68,) (18,)


In [196]:
model = LinearDiscriminantAnalysis()
model.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [197]:
print(model.predict_proba(X_test[10:13]))
print(y_test[10:13])

[[9.99999394e-01 0.00000000e+00 6.05051094e-07 1.03714467e-09
  2.13768668e-11]
 [2.84335610e-08 0.00000000e+00 4.57497585e-02 9.53364243e-01
  8.85969925e-04]
 [6.90156456e-01 0.00000000e+00 2.75351101e-01 2.17359735e-02
  1.27564695e-02]]
[0 3 2]


In [153]:
scores = cross_val_score(model, X, y, cv=6)
print('Mean Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Mean Accuracy: 0.802 (0.094)


In [154]:
#       :)
s = pickle.dumps(model)
clf2 = pickle.loads(s)
y_true = y_test
y_pred = clf2.predict(X_test)
confusion_matrix(y_true, y_pred)

array([[5, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 3, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 4]])

In [155]:
model.fit(X,y)

LinearDiscriminantAnalysis()

In [156]:
dump(model, 'models/EMG_LDA.joblib')

['models/EMG_LDA.joblib']

In [157]:
EMG_LDA = load('models/EMG_LDA.joblib')
print(EMG_LDA.predict(X[2:5]))
print(y[2:5])

[0 0 0]
[0 0 0]
