In [13]:
#baum_300_sigmoid
import numpy as np
load = np.load('data/baum_300_sigmoid.npz',allow_pickle=True)

training_score = load['x']
testing_score = load['y']

training_score = np.transpose(training_score)
testing_score = np.transpose(testing_score)


print('testing_score loss:', np.mean(testing_score[0]))
print('testing_score accuracy:',np.mean(testing_score[1]))



testing_score loss: 1.5965251127878826
testing_score accuracy: 0.3710015167792638


In [14]:
#baum_300_softmax
import numpy as np
load = np.load('data/baum_300_softmax.npz',allow_pickle=True)

training_score = load['x']
testing_score = load['y']

training_score = np.transpose(training_score)
testing_score = np.transpose(testing_score)


print('testing_score loss:', np.mean(testing_score[0]))
print('testing_score accuracy:',np.mean(testing_score[1]))



testing_score loss: 1.6178172032038372
testing_score accuracy: 0.3749220321575801


In [15]:
#ravdess_300_sigmoid
import numpy as np
load = np.load('data/ravdess_300_sigmoid.npz',allow_pickle=True)

training_score = load['x']
testing_score = load['y']

training_score = np.transpose(training_score)
testing_score = np.transpose(testing_score)


print('testing_score loss:', np.mean(testing_score[0]))
print('testing_score accuracy:',np.mean(testing_score[1]))



testing_score loss: 0.2088899090886116
testing_score accuracy: 0.8076388736565908


In [16]:
#ravdess_300_softmax
import numpy as np
load = np.load('data/ravdess_300_softmax.npz',allow_pickle=True)

training_score = load['x']
testing_score = load['y']

training_score = np.transpose(training_score)
testing_score = np.transpose(testing_score)


print('testing_score loss:', np.mean(testing_score[0]))
print('testing_score accuracy:',np.mean(testing_score[1]))



testing_score loss: 0.19432383030653
testing_score accuracy: 0.7944444417953491


In [1]:
#baum 30 sigomoid
import pickle
with (open('pickle_files/baum_30_sigmoid.pckl', "rb")) as openfile:
    while True:
        try:
            print(pickle.load(openfile))
        except EOFError:
            break

[[0.23872889578342438, 0.8775981664657593], 'training accuracy fold #0']
[[1.0916067361831665, 0.3333333432674408], 'testing accuracy fold #0']
[[ 0  0  0  2  1  0]
 [ 1  4  1  6  4  3]
 [ 0  0  1  1  3  0]
 [ 3  6  2 14  4  2]
 [ 4  1  0  4  8  2]
 [ 2  2  1  2  1  2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.31      0.21      0.25        19
           2       0.20      0.20      0.20         5
           3       0.48      0.45      0.47        31
           4       0.38      0.42      0.40        19
           5       0.22      0.20      0.21        10

    accuracy                           0.33        87
   macro avg       0.27      0.25      0.25        87
weighted avg       0.36      0.33      0.34        87

[[0.2626546323299408, 0.8729792237281799], 'training accuracy fold #1']
[[1.0240159034729004, 0.4137931168079376], 'testing accuracy fold #1']
[[ 2  0  1  3  1  1]
 [ 0  4  2  0  2  0]
 

In [2]:
#baum 30 softmax
import pickle
with (open('pickle_files/baum_30_softmax.pckl', "rb")) as openfile:
    while True:
        try:
            print(pickle.load(openfile))
        except EOFError:
            break

[[0.25092217326164246, 0.8729792237281799], 'training accuracy fold #0']
[[1.0814522504806519, 0.3218390941619873], 'testing accuracy fold #0']
[[ 0  1  0  1  1  0]
 [ 1  4  1  7  4  2]
 [ 0  0  2  2  1  0]
 [ 5  4  5 12  4  1]
 [ 3  1  2  3  8  2]
 [ 1  1  1  3  2  2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.36      0.21      0.27        19
           2       0.18      0.40      0.25         5
           3       0.43      0.39      0.41        31
           4       0.40      0.42      0.41        19
           5       0.29      0.20      0.24        10

    accuracy                           0.32        87
   macro avg       0.28      0.27      0.26        87
weighted avg       0.36      0.32      0.33        87

[[0.2753412425518036, 0.886836051940918], 'training accuracy fold #1']
[[1.044571042060852, 0.4597701132297516], 'testing accuracy fold #1']
[[ 1  1  1  2  2  1]
 [ 0  5  1  0  2  0]
 [ 

In [5]:
#ravdess 30 sigmoid
import pickle
with (open('pickle_files/ravdess_30_sigmoid.pckl', "rb")) as openfile:
    while True:
        try:
            print(pickle.load(openfile))
        except EOFError:
            break

[[0.3336029648780823, 0.8650000095367432], 'training accuracy fold #0']
[[0.43974587321281433, 0.7833333611488342], 'testing accuracy fold #0']
[[15  0  0  1  0  1  0  0]
 [ 0 32  0  2  1  1  0  2]
 [ 0  0 22  3  1  4  0  2]
 [ 2  0  2 19  5  2  0  0]
 [ 0  0  0  1 27  2  1  0]
 [ 2  2  0  0  2 20  2  0]
 [ 0  0  0  2  2  1 25  0]
 [ 0  0  2  0  1  1  2 28]]
              precision    recall  f1-score   support

           1       0.79      0.88      0.83        17
           2       0.94      0.84      0.89        38
           3       0.85      0.69      0.76        32
           4       0.68      0.63      0.66        30
           5       0.69      0.87      0.77        31
           6       0.62      0.71      0.67        28
           7       0.83      0.83      0.83        30
           8       0.88      0.82      0.85        34

    accuracy                           0.78       240
   macro avg       0.79      0.79      0.78       240
weighted avg       0.79      0.78      0.78

In [6]:
#ravdess 30 softmax
import pickle
with (open('pickle_files/ravdess_30_softmax.pckl', "rb")) as openfile:
    while True:
        try:
            print(pickle.load(openfile))
        except EOFError:
            break

[[0.38627323508262634, 0.8650000095367432], 'training accuracy fold #0']
[[0.5373510718345642, 0.7708333134651184], 'testing accuracy fold #0']
[[15  0  0  1  0  1  0  0]
 [ 0 32  1  3  0  1  0  1]
 [ 0  2 19  1  1  2  0  7]
 [ 2  0  0 21  4  2  0  1]
 [ 0  0  0  6 23  2  0  0]
 [ 2  2  0  0  2 20  2  0]
 [ 0  1  0  0  1  3 25  0]
 [ 0  0  0  0  1  1  2 30]]
              precision    recall  f1-score   support

           1       0.79      0.88      0.83        17
           2       0.86      0.84      0.85        38
           3       0.95      0.59      0.73        32
           4       0.66      0.70      0.68        30
           5       0.72      0.74      0.73        31
           6       0.62      0.71      0.67        28
           7       0.86      0.83      0.85        30
           8       0.77      0.88      0.82        34

    accuracy                           0.77       240
   macro avg       0.78      0.77      0.77       240
weighted avg       0.78      0.77      0.77