In [13]:
#Functional API fusion model
import keras
import tensorflow
#tensorflow.debugging.set_log_device_placement(True)
#print("Num GPUs Available: ", len(tensorflow.config.list_physical_devices('GPU')))
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.models import Model

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Flatten
from keras.layers import BatchNormalization
from keras.layers import Conv1D
from keras.layers import Conv2D
from keras.layers import Conv2DTranspose
from keras.layers import Conv3D
from keras.layers import LeakyReLU
from keras.layers import Dropout
from keras.layers import MaxPooling2D
from keras.layers import GlobalAveragePooling2D
from keras.layers import Concatenate
from keras.layers import Input
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.metrics import classification_report, confusion_matrix
import datetime
from sklearn.model_selection import KFold
import pickle
from sklearn.utils import shuffle
import sys
np.set_printoptions(threshold=1000)

In [14]:
#gpus = tensorflow.config.list_physical_devices('GPU')


strategy = tensorflow.distribute.MirroredStrategy(devices=["/gpu:2","/gpu:3"])

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')


In [15]:
load = np.load('data/BAUM_all.npz',allow_pickle=True)
audio = load['audio']
video = load['video']
labels = load['labels']
print(labels.shape)
n_splits = 6
print(np.array(video.shape))

(747,)
[747 115 128 128]


In [16]:
#video pre-process

fraction = 5
frames = int(115/fraction) #115
shape = (128,128,frames,1)

video = np.reshape(video,(video.shape[0], 115, 128, 128, 1))

reshape_videos = []

for i in video:
    single_video = []
    for j in range( i.shape[0] ): #HEREi.shape[0]
        if(  j % fraction == 0 ):
            single_video.append( i[j] )
    reshape_videos.append( single_video )

video = np.array(reshape_videos)
del reshape_videos

print(video.shape)

#frames = 115
video_input = (frames, 128, 128, 1)
video_shape = (video.shape[0],frames, 128, 128, 1)
video = np.reshape(video, video_shape)
print(video.shape)

(747, 23, 128, 128, 1)
(747, 23, 128, 128, 1)


In [17]:
#audio pre-process
num_rows = 84672
num_columns = 1
num_channels = 1

audio_input = (num_rows, num_columns)
audio_shape = (audio.shape[0], num_rows, num_columns)
audio = np.reshape(audio, audio_shape)
print(audio.shape)

(747, 84672, 1)


In [18]:
#labels = labels - 1
#print(labels[101])
labels = to_categorical(labels)
target_names = ['neutral', 'calm', 'happy', 'sad', 'angry', 'fearful', 'disgust', 'surprised']

"""
v_train, v_test, a_train, a_test, l_train, l_test = train_test_split(video, 
                                                                     audio, 
                                                                     labels,
                                                                     test_size=0.166,
                                                                     random_state=42) #size=0.2

print(v_train.shape)
print(l_train[95])
print(a_train.shape)
"""

'\nv_train, v_test, a_train, a_test, l_train, l_test = train_test_split(video, \n                                                                     audio, \n                                                                     labels,\n                                                                     test_size=0.166,\n                                                                     random_state=42) #size=0.2\n\nprint(v_train.shape)\nprint(l_train[95])\nprint(a_train.shape)\n'

In [19]:
#Audio Network
def audio_cnn_1d(input_):
    #Layer 1
    conv1d = Conv1D(padding='same', filters=25, kernel_size=64, strides = 8, input_shape=audio_input)(input_)
    relu = LeakyReLU(alpha=0.2)(conv1d)
    
    #Layer 2
    conv1d = Conv1D(padding='same', filters=25, kernel_size=128, strides = 8)(relu)
    batch = BatchNormalization()(conv1d)
    relu = LeakyReLU(alpha=0.2)(batch)
    
    #Layer 3
    conv1d = Conv1D(padding='same', filters=25, kernel_size=256, strides = 8)(relu)
    batch = BatchNormalization()(conv1d)
    relu = LeakyReLU(alpha=0.2)(batch)
    
    #Layer 4
    conv1d = Conv1D(padding='same', filters=25, kernel_size=512, strides = 4)(relu)
    batch = BatchNormalization()(conv1d)
    relu = LeakyReLU(alpha=0.2)(batch)
    
    #Layer 5
    conv1d = Conv1D(padding='same', filters=25, kernel_size=1024, strides = 4)(relu)
    batch = BatchNormalization()(conv1d)
    relu = LeakyReLU(alpha=0.2)(relu)
    
    #layer 6
    output = Flatten()(relu)
    
    return output

In [20]:
#video neural network
def video_cnn_3d(input_):
    #layer 1
    conv3d = Conv3D(64, kernel_size=(3,3,3), strides=(2,2,1), input_shape=video_input)(input_)
    relu = LeakyReLU(alpha=0.2)(conv3d)
    
    #layer 2
    conv3d = Conv3D(128, kernel_size=(3,3,3), strides=(2,2,1), padding='SAME')(relu)
    batch = BatchNormalization()(conv3d)
    relu = LeakyReLU(alpha=0.2)(batch)
    
    #layer 3
    conv3d = Conv3D(256, kernel_size=(3,3,3), strides=(2,2,1), padding='SAME')(relu)
    batch = BatchNormalization()(conv3d)
    relu = LeakyReLU(alpha=0.2)(batch)

    #layer 4
    conv3d = Conv3D(512, kernel_size=(3,3,3), strides=(2,2,2), padding='SAME')(relu)
    batch = BatchNormalization()(conv3d)
    relu = LeakyReLU(alpha=0.2)(batch)

    #layer 5
    conv3d = Conv3D(1024, kernel_size=(3,3,3), strides=(2,2,2), padding='SAME')(relu)
    batch = BatchNormalization()(conv3d)
    relu = LeakyReLU(alpha=0.2)(batch)

    #layer 6
    conv3d = Conv3D(2048, kernel_size=(3,3,3), strides=(2,2,2), padding='SAME')(relu)
    batch = BatchNormalization()(conv3d)
    relu = LeakyReLU(alpha=0.2)(batch)

    #layer 7
    output = Flatten()(relu)
    return output


In [22]:
#k-Fold training, set for 6 splits

n = 0 #current fold

epochs = 30
function = 'softmax'
name = 'baum_' + str(epochs) + '_' + 'acted' 
pickle_file = 'pickle_files/' + name + '.pckl'

training_score = []
testing_score = []

f = open(pickle_file, 'wb') #file for saving information/data about each fold


kf = KFold(n_splits,shuffle=True,random_state=42)
kf.get_n_splits(audio)

print(kf)

print(audio.shape)
print(labels.shape)

kf = KFold(n_splits,shuffle=True,random_state=42)
kf.get_n_splits(audio)

for train_index, test_index in kf.split(audio):
    print('Beginning fold #' + str(n) + '...')
    #print(train_index)
    #print(test_index)
    a_train, a_test = audio[train_index], audio[test_index]
    v_train, v_test = video[train_index], video[test_index]
    l_train, l_test = labels[train_index], labels[test_index]
    
    
    with strategy.scope():
        #fusion layer
        aud = Input(audio_input)
        vid = Input(video_input)

        audio_tensor = audio_cnn_1d(aud)

        video_tensor = video_cnn_3d(vid)

        fusion = Concatenate()([audio_tensor, video_tensor]) #combining tensors
        batch = BatchNormalization()(fusion)
        prediction = Dense(2,activation=function)(batch) #softmax
        twin_net = Model(inputs=[aud,vid], outputs=prediction)

        #Training

        checkpoint_filepath = 'models/' + name
        model_checkpoint_callback = ModelCheckpoint(
            filepath=checkpoint_filepath,
            period=10
            )
        log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") + checkpoint_filepath
        tensorboard_callback = tensorflow.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

        twin_net.compile(loss='categorical_crossentropy', #categorical_crossentropy
                optimizer=optimizers.Adam(lr=0.00001), 
                         metrics=['accuracy'])

        #twin_net.summary()


        twin_net.fit([a_train,v_train], l_train,
                batch_size=31,
                epochs=epochs,
                verbose=1,
                validation_split=0.166,
                callbacks=[model_checkpoint_callback,
                tensorboard_callback])
        
        score = twin_net.evaluate([a_train, v_train], l_train, verbose=0)
        pickle.dump([score, 'training accuracy fold #' + str(n)], f)
        training_score.append(score)

        score = twin_net.evaluate([a_test, v_test], l_test, verbose=0)
        pickle.dump([score, 'testing accuracy fold #' + str(n)], f)
        testing_score.append(score)

        Y_pred = twin_net.predict([a_test, v_test])
        y_pred = np.argmax(Y_pred, axis=1)
        labels_ = np.argmax(l_test, axis=1)
        pickle.dump(confusion_matrix(labels_, y_pred), f)
        pickle.dump(classification_report(labels_, y_pred), f)
        
        n+=1

np.savez('data/'+name,x=training_score,y=testing_score)
f.close()




KFold(n_splits=6, random_state=42, shuffle=True)
(747, 84672, 1)
(747, 2)
Beginning fold #0...


/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/30
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
17/17 [==============================] - 19s 661ms/step - loss: 1.4044 - accuracy: 0.5193 - val_loss: 0.6594 - val_accuracy: 0.7885
Epoch 2/30
17/17 [==============================] - 7s 412ms/step - loss: 1.5885 - accuracy: 0.4961 - val_loss: 0.7979 - val_accuracy: 0.0385
Epoch 3/30
17/17 [==============================] - 7s 403ms/step - loss: 1.1750 - accuracy: 0.5058 - val_loss: 0.6793 - val_accuracy: 0.5577
Epoch 4/30
17/17 [==============================] - 7s 405ms/step - loss: 1.0394 - accuracy: 0.5405 - val_loss: 0.5464 - val_accuracy: 0.9808
Epoch 5/30
17/17 [==============================] - 7s 405ms/step - loss: 0.9883 - accuracy: 0.5541 - val_loss: 0.4396 - val_accuracy: 1.0000
Epoch 6/30
17/17 [==============================] - 7s 401ms/step - loss: 0.9533 - accuracy: 0.5869 - val_loss: 0.559

/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

Beginning fold #1...


/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/30
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
17/17 [==============================] - 19s 656ms/step - loss: 1.3126 - accuracy: 0.5174 - val_loss: 0.7094 - val_accuracy: 0.4038
Epoch 2/30
17/17 [==============================] - 7s 390ms/step - loss: 1.5526 - accuracy: 0.5019 - val_loss: 0.4796 - val_accuracy: 1.0000
Epoch 3/30
17/17 [==============================] - 7s 390ms/step - loss: 1.1190 - accuracy: 0.5598 - val_loss: 0.4108 - val_accuracy: 1.0000
Epoch 4/30
17/17 [==============================] - 7s 394ms/step - loss: 1.0539 - accuracy: 0.5598 - val_loss: 0.2942 - val_accuracy: 1.0000
Epoch 5/30
17/17 [==============================] - 7s 409ms/step - loss: 0.9162 - accuracy: 0.5656 - val_loss: 0.2826 - val_accuracy: 1.0000
Epoch 6/30
17/17 [==============================] - 7s 399ms/step - loss: 0.9010 - accuracy: 0.5927 - val_loss: 0.250

/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

Beginning fold #2...


/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/30
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
17/17 [==============================] - 19s 623ms/step - loss: 1.3483 - accuracy: 0.5097 - val_loss: 0.6214 - val_accuracy: 0.9615
Epoch 2/30
17/17 [==============================] - 7s 393ms/step - loss: 1.6867 - accuracy: 0.4903 - val_loss: 0.6192 - val_accuracy: 0.8750
Epoch 3/30
17/17 [==============================] - 7s 393ms/step - loss: 1.2495 - accuracy: 0.5347 - val_loss: 0.5586 - val_accuracy: 1.0000
Epoch 4/30
17/17 [==============================] - 7s 399ms/step - loss: 1.1063 - accuracy: 0.5251 - val_loss: 0.6151 - val_accuracy: 0.9327
Epoch 5/30
17/17 [==============================] - 7s 396ms/step - loss: 0.9166 - accuracy: 0.5676 - val_loss: 0.5784 - val_accuracy: 0.9712
Epoch 6/30
17/17 [==============================] - 7s 390ms/step - loss: 0.9208 - accuracy: 0.5598 - val_loss: 0.296

/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

Beginning fold #3...


/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/30
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 40 all-reduces with algorithm = nccl, num_packs = 1
17/17 [==============================] - 24s 957ms/step - loss: 1.2156 - accuracy: 0.5183 - val_loss: 0.7037 - val_accuracy: 0.4231
Epoch 2/30
17/17 [==============================] - 7s 393ms/step - loss: 1.5685 - accuracy: 0.4971 - val_loss: 0.6872 - val_accuracy: 0.5288
Epoch 3/30
17/17 [==============================] - 7s 392ms/step - loss: 1.1884 - accuracy: 0.5202 - val_loss: 0.5300 - val_accuracy: 1.0000
Epoch 4/30
17/17 [==============================] - 7s 390ms/step - loss: 1.0459 - accuracy: 0.5645 - val_loss: 0.5275 - val_accuracy: 0.9904
Epoch 5/30
17/17 [==============================] - 7s 392ms/step - loss: 0.9765 - accuracy: 0.5395 - val_loss: 0.5658 - val_accuracy: 0.9327
Epoch 6/30
17/17 [==============================] - 7s 391ms/step - loss: 0.8881 - accuracy: 0.5780 - val_loss: 0.491

/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

Beginning fold #4...


/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/30
17/17 [==============================] - 19s 658ms/step - loss: 1.2167 - accuracy: 0.4913 - val_loss: 0.6555 - val_accuracy: 0.8173
Epoch 2/30
17/17 [==============================] - 7s 390ms/step - loss: 1.5040 - accuracy: 0.5395 - val_loss: 0.5856 - val_accuracy: 0.9327
Epoch 3/30
17/17 [==============================] - 7s 394ms/step - loss: 1.1970 - accuracy: 0.4971 - val_loss: 0.5738 - val_accuracy: 0.9904
Epoch 4/30
17/17 [==============================] - 7s 388ms/step - loss: 1.0286 - accuracy: 0.5222 - val_loss: 0.8877 - val_accuracy: 0.0000e+00
Epoch 5/30
17/17 [==============================] - 7s 389ms/step - loss: 0.9636 - accuracy: 0.5665 - val_loss: 0.7739 - val_accuracy: 0.2308
Epoch 6/30
17/17 [==============================] - 7s 390ms/step - loss: 0.9412 - accuracy: 0.5665 - val_loss: 1.2369 - val_accuracy: 0.0000e+00
Epoch 7/30
17/17 [==============================] - 7s 390ms/step - loss: 0.8466 - accuracy: 0.5896 - val_loss: 0.8915 - val_accuracy: 0.06

/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

Beginning fold #5...


/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/30
17/17 [==============================] - 19s 618ms/step - loss: 1.5149 - accuracy: 0.5048 - val_loss: 0.6296 - val_accuracy: 0.8846
Epoch 2/30
17/17 [==============================] - 7s 391ms/step - loss: 1.7188 - accuracy: 0.5183 - val_loss: 0.7348 - val_accuracy: 0.2404
Epoch 3/30
17/17 [==============================] - 7s 392ms/step - loss: 1.1500 - accuracy: 0.5299 - val_loss: 0.6291 - val_accuracy: 0.8462
Epoch 4/30
17/17 [==============================] - 7s 394ms/step - loss: 0.9869 - accuracy: 0.5414 - val_loss: 0.6222 - val_accuracy: 0.8365
Epoch 5/30
17/17 [==============================] - 7s 402ms/step - loss: 0.9458 - accuracy: 0.5511 - val_loss: 0.6046 - val_accuracy: 0.7788
Epoch 6/30
17/17 [==============================] - 7s 397ms/step - loss: 0.9069 - accuracy: 0.5819 - val_loss: 0.5929 - val_accuracy: 0.8269
Epoch 7/30
17/17 [==============================] - 7s 390ms/step - loss: 0.8995 - accuracy: 0.5819 - val_loss: 0.6487 - val_accuracy: 0.6538
Epoch

/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/s/duff/b/homes/RUIZLAB/danieldel/projects/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

In [24]:
#k_fold testing results
print('data/'+name+'.npz')
load = np.load('data/'+name+'.npz',allow_pickle=True)

training_score = load['x']
testing_score = load['y']



training_score = np.transpose(training_score)
testing_score = np.transpose(testing_score)

print('testing_score loss:', np.mean(training_score[0]))
print('testing_score accuracy:',np.mean(training_score[1]))

print('testing_score loss:', np.mean(testing_score[0]))
print('testing_score accuracy:',np.mean(testing_score[1]))



data/baum_30_acted.npz
testing_score loss: 0.1956578108171622
testing_score accuracy: 0.9705617427825928
testing_score loss: 0.2207652727762858
testing_score accuracy: 0.9476774136225382


In [ ]:
load = np.load('data/'+name+'.npz')
training_score = load['x']
testing_score = load['y']

print(training_score,testing_score)

f.close()

with (open(pickle_file, "rb")) as openfile:
    while True:
        try:
            print(pickle.load(openfile))
        except EOFError:
            break

In [ ]:
soft 300 epoch
Training Accuracy:  [1.4789059162139893, 0.9099307060241699]
Testing Accuracy:  [11.502437591552734, 0.4137931168079376]
Confusion_Matrix
[[ 0  1  0  0  2  0]
 [ 2  6  0  6  4  1]
 [ 0  1  1  1  1  1]
 [ 2  6  0 16  6  1]
 [ 3  1  0  2 11  2]
 [ 0  1  0  3  4  2]]

sig 300 epoch
Training Accuracy:  [0.12294566631317139, 0.912240207195282]
Testing Accuracy:  [1.0002453327178955, 0.4252873659133911]
Confusion_Matrix
[[ 0  1  0  0  2  0]
 [ 1  5  1  7  5  0]
 [ 0  1  2  1  1  0]
 [ 2  5  1 18  4  1]
 [ 3  0  0  4 11  1]
 [ 2  1  0  2  4  1]]

baum basic 6 softmax
Training Accuracy:  [0.459194540977478, 0.9053117632865906]
Testing Accuracy:  [3.032977819442749, 0.3563218414783478]
Confusion_Matrix
[[ 0  0  0  0  2  1]
 [ 1  3  0  9  3  3]
 [ 0  1  1  1  1  1]
 [ 1  4  2 20  4  0]
 [ 5  2  0  4  6  2]
 [ 1  1  0  4  3  1]]

Baum basic 6 sigmoid
Training Accuracy:  [0.27888423204421997, 0.9053117632865906]
Testing Accuracy:  [0.9529832601547241, 0.40229883790016174]
Confusion_Matrix
[[ 0  1  0  1  1  0]
 [ 1  5  1  7  4  1]
 [ 0  1  2  1  1  0]
 [ 2  6  3 17  2  1]
 [ 4  0  0  4  9  2]
 [ 0  1  0  4  3  2]]

Baum all
Training Accuracy:  [0.27805307507514954, 0.8719576597213745]
Testing Accuracy:  [0.8749507665634155, 0.24338623881340027]
Confusion_Matrix
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  1  3  1  2  1  0  0]
 [ 0  0  2  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  1  1  0  1  2  1  2  3  4  0  2  0]
 [ 0  0  0  0  2  0  1  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  1  0]
 [ 0  0  1  1  0  0  4  2  1  1  2  0  0  0]
 [ 0  0  2  0  0  0  0  1  0  1  2  0  0  0]
 [ 1  4  0  0  1  1  4  1  9  3  2  0  3  0]
 [ 0  0  1  1  1  0  2  1  2 10  2  2  4  3]
 [ 0  3  0  0  0  0  4  0  1  5  7  2  0  1]
 [ 0  2  1  1  0  0  3  1  1  0  0  0  0  1]
 [ 0  0  0  1  2  1  0  2  1  7  3  2  3  2]
 [ 0  0  0  0  0  0  2  0  0  2  6  1  2  6]]